apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.33.0
overrides:
- image: quay.io/jetstack/cert-manager-cainjector:v1.4.1
  newImage: quay.io/jetstack/cert-manager-cainjector@sha256:95660bc46e382bf4c79a9eb498dd1517b34ca759a70f2016d45d3376c9dcf8a6
  preresolved: true
- image: quay.io/jetstack/cert-manager-controller:v1.4.1
  newImage: quay.io/jetstack/cert-manager-controller@sha256:6e8f2789da655824de49f1cfffd8e22458ad07d29477b96459550ed9418527e4
  preresolved: true
- image: quay.io/jetstack/cert-manager-webhook:v1.4.1
  newImage: quay.io/jetstack/cert-manager-webhook@sha256:30f1d11a80e29ce7c827bb41201b9f1ad9026e2a6f45665b2752071d1c8888ac
  preresolved: true
