---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: kpack
  namespace: nebhale-system
spec:
  serviceAccountName: kapp
  packageRef:
    refName: kpack.nebhale.io
    versionSelection:
      constraints: 0.6.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack
  namespace: nebhale-system
imagePullSecrets:
  - name: ecr-credentials

---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
diffAgainstLastAppliedFieldExclusionRules:
- path: [secrets]
  resourceMatchers:
  - kindNamespaceNameMatcher: {kind: ServiceAccount, namespace: nebhale-system, name: kpack}
