apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: nebhale
  namespace: nebhale-system
spec:
  fetch:
    git:
      url: https://github.com/nebhale/kubernetes
      ref: origin/main
      subPath: repository
