---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: nebhale
  namespace: nebhale-system
spec:
  fetch:
    git:
      url: https://github.com/nebhale/kubernetes
      ref: origin/main
      subPath: repository

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: kpack
  namespace: nebhale-system
spec:
  serviceAccountName: kapp
  packageRef:
    refName: kpack.nebhale.io
    versionSelection:
      constraints: 0.6.0
