---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nebhale
  region: us-west-1
  version: "1.22"

iam:
  withOIDC: true

secretsEncryption:
  keyARN: arn:aws:kms:us-west-1:660407540157:key/4e86884f-2ae0-453a-a4f2-652343f5afa8

kubernetesNetworkConfig:
  ipFamily: IPv4

managedNodeGroups:
- name: default
  desiredCapacity: 2
  minSize: 2
  maxSize: 2
