apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nebhale
  region: us-west-1
  version: "1.22"

iam:
  withOIDC: true

kubernetesNetworkConfig:
  ipFamily: IPv4

managedNodeGroups:
- name: default
  desiredCapacity: 2
  minSize: 2
  maxSize: 2
