#@ load("@ytt:data", "data")
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: #@ "default.{}".format(data.values.version)
spec:
  id: io.buildpacks.stacks.bionic
  buildImage:
    image: #@ "public.ecr.aws/w7f4x4f0/stacks/build:{}".format(data.values.version)
  runImage:
    image: #@ "public.ecr.aws/w7f4x4f0/stacks/run:{}".format(data.values.version)
