apiVersion: v1
kind: Namespace
metadata:
  name: nebhale-system

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cluster-content
  namespace: nebhale-system
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting rbac"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting rbac"
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: https://github.com/nebhale/kubernetes
      ref: origin/main
      subPath: config
      secretRef:
        name: github-credentials
  template:
  - ytt: {}
  - kbld: {}
  deploy:
  - kapp: {}

#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: nebhale-system
stringData:
  username: #@ data.values.GITHUB.USERNAME
  password: #@ data.values.GITHUB.PASSWORD

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp
  namespace: nebhale-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kapp-cluster-role
  namespace: default
subjects:
- kind: ServiceAccount
  name: kapp
  namespace: nebhale-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
diffAgainstLastAppliedFieldExclusionRules:
- path: [secrets]
  resourceMatchers:
  - kindNamespaceNameMatcher: {kind: ServiceAccount, namespace: nebhale-system, name: kapp}
