apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.33.0
overrides:
- image: quay.io/jetstack/cert-manager-cainjector:v1.4.0
  newImage: quay.io/jetstack/cert-manager-cainjector@sha256:a24ab35640bb9ddd58a0801e8021bec68e0ab247d62ea10c69d86506097e9eaa
  preresolved: true
- image: quay.io/jetstack/cert-manager-controller:v1.4.0
  newImage: quay.io/jetstack/cert-manager-controller@sha256:85f03d2ffdfd53f4dab53147b3192a5322a3300b5368f60416e7b838e65f42d1
  preresolved: true
- image: quay.io/jetstack/cert-manager-webhook:v1.4.0
  newImage: quay.io/jetstack/cert-manager-webhook@sha256:f91867a7769436d72e6f4bb68e4e3d240d93d5bc8cd59742298a2a2b3ccf11b7
  preresolved: true
